// <auto-generated />
using System;
using DotNetScaServerData.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetScaServerData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetScaServerData.Models.NuGetLoads", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoadCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NuGetLoads");
                });

            modelBuilder.Entity("DotNetScaServerData.Models.NuGetPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoadRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.Property<string>("PackageVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoadRequestId");

                    b.ToTable("NuGetPackages");
                });

            modelBuilder.Entity("DotNetScaServerData.Models.NuGetPackageToLoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AddTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoading")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LoadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.Property<string>("PackageVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NuGetPackageToLoads");
                });

            modelBuilder.Entity("DotNetScaServerData.Models.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("bytea");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("DotNetScaServerData.Models.UserAuthentication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GeneratedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserAuthentications");
                });

            modelBuilder.Entity("DotNetScaServerData.Models.NuGetPackage", b =>
                {
                    b.HasOne("DotNetScaServerData.Models.NuGetPackageToLoad", "LoadRequest")
                        .WithMany()
                        .HasForeignKey("LoadRequestId");

                    b.Navigation("LoadRequest");
                });

            modelBuilder.Entity("DotNetScaServerData.Models.Signature", b =>
                {
                    b.HasOne("DotNetScaServerData.Models.NuGetPackage", "Package")
                        .WithMany("Signatures")
                        .HasForeignKey("PackageId");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("DotNetScaServerData.Models.NuGetPackage", b =>
                {
                    b.Navigation("Signatures");
                });
#pragma warning restore 612, 618
        }
    }
}
